import {icon,button,categoryIcon,header,esc,empty,ratingLabel} from '../ui.js';
import {latest,dayKey} from '../engine.js';
import {md} from '../markdown.js';
import {foundationLessonCards} from './foundation.js';
export function topic(ctx,id){const t=ctx.topics.find(t=>t.id===id);if(!t)return empty('Search','教材が見つかりません','カテゴリから選び直してください。');const c=ctx.categories.find(c=>c.id===t.category),qs=ctx.questions.filter(q=>q.topic===id);const chapters=[...t.markdown.matchAll(/^## (\d+)\. (.*)$/gm)];const fCards=foundationLessonCards(ctx,id);const activeFoundation=ctx.foundationState?.session&&ctx.foundationState.session.step!=='done';return `${header(t.title,c.title,`#/category/${c.id}`)}<div class="article-tools">${button(`${icon('Play')}実践問題を学ぶ`,'start','primary',`data-topic="${id}" data-category="${c.id}"`)}<a class="btn secondary" href="${t.url}" target="_blank" rel="noopener noreferrer">元サイト ${icon('ExternalLink')}</a>${ctx.state.session&&ctx.state.session.phase!=='done'?'<a class="btn secondary" href="#/study">実践編の学習に戻る</a>':''}${activeFoundation?'<a class="btn secondary" href="#/foundation-study">基礎レッスンに戻る</a>':''}</div>${ctx.selectedMode==='foundations'?fCards:''}<details class="toc"><summary>目次 · ${chapters.length}章${icon('ChevronRight')}</summary><div>${chapters.map(([,n,title])=>`<button data-action="chapter" data-chapter="${n}">${n}. ${esc(title)}</button>`).join('')}</div></details><article class="prose article-body">${md(t.markdown.replace(/^# .*\n/,''))}</article>${ctx.selectedMode!=='foundations'?fCards:''}<section class="panel"><h2>理解を確かめる（実践編）</h2><p class="muted">このトピックの5問</p><div class="topic-questions">${qs.map(q=>`<button data-action="single" data-question="${q.id}"><span>${q.label}</span>${esc(q.prompt)}${icon('ChevronRight')}</button>`).join('')}</div></section>`;}
export function study(ctx){const s=ctx.state.session;if(!s)return empty('BookOpen','学習を始めましょう','復習と新しい問題を、あなたのペースで。',button('学習を始める','start','primary'));
 if(s.phase==='done')return complete(ctx);
 const q=ctx.questions.find(q=>q.id===s.pending[0]);if(!q)return empty('Info','教材が更新されました','この学習を終了して、新しい問題を選んでください。',button('学習を終了','finish','primary'));
 const c=ctx.categories.find(c=>c.id===q.category),t=ctx.topics.find(t=>t.id===q.topic);const bookmarked=ctx.state.bookmarks.includes(q.id),showAnswer=['answer','feedback'].includes(s.phase);const e=ctx.state.events.find(e=>e.id===s.lastEvent);const previous=latest(ctx.state.events,{scheduled:true}).get(q.id);const isPractice=s.practice||Boolean(previous?.due>dayKey());
 return `<div class="study-shell"><div class="study-top"><a class="icon-button" href="#/home" aria-label="学習を中断してホームへ">${icon('ChevronLeft')}</a><div><span>${Math.min(s.completed.length+(s.phase==='feedback'?0:1),s.total)} <span class="muted">/ ${s.total}</span></span><small>${isPractice?'自主練習':s.category?'カテゴリ学習':'集中学習'}</small></div><button class="icon-button" data-action="end-session" aria-label="今回の学習を終了">${icon('X')}</button></div><div class="study-progress"><span style="width:${s.completed.length/s.total*100}%;background:${showAnswer?'var(--purple)':'var(--blue)'}"></span></div><div class="study-meta"><span class="category-tag" style="--color:${c.color}">${icon(c.icon)}${c.title}</span><button class="icon-button bookmark ${bookmarked?'saved':''}" data-action="bookmark" data-question="${q.id}" aria-label="${bookmarked?'ブックマークを解除':'ブックマークに追加'}" aria-pressed="${bookmarked}">${icon('Bookmark')}</button></div>
 ${s.phase==='feedback'?feedback(q,e):`<div class="question-heading"><p>${t.title}<span>${q.type==='choice'?'選択式':q.label}</span></p><h1>${esc(q.prompt)}</h1></div>`}
 ${q.type==='choice'&&s.phase==='question'?`<fieldset class="choices"><legend class="sr-only">回答を選択</legend>${q.choices.map((opt,i)=>`<label class="choice ${s.selected===opt.id?'selected':''}"><input type="radio" name="answer" value="${opt.id}" ${s.selected===opt.id?'checked':''}><span class="choice-letter">${String.fromCharCode(65+i)}</span><span>${esc(opt.text)}</span></label>`).join('')}</fieldset>`:''}
 ${q.type==='explain'&&s.phase==='question'?`<div class="thinking-space"><span>${icon('BookOpen')}</span><p>まずは、自分の言葉で。</p><small>声に出して、または頭の中で説明してみましょう。</small></div>`:''}
 ${showAnswer?`<section class="answer-panel"><div class="answer-label">${icon('CheckCircle2')}模範回答</div><div class="prose concise">${md(q.summary)}</div>${q.points.length?`<div class="answer-points"><h2>押さえたい要点</h2><ul>${q.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul></div>`:''}<details class="detail-explanation"><summary>詳しい解説 ${icon('ChevronRight')}</summary><div class="prose">${md(q.detail)}</div></details><a class="source-link" href="#/topic/${q.topic}?chapter=${q.chapter}">${icon('FileText')}出典：${t.title} · 第${q.chapter}章 ${icon('ChevronRight')}</a><p class="source-origin">${q.origin}</p></section>`:''}
 ${s.phase==='question'?`<div class="study-footer">${button('スキップ','skip','secondary')}${button(q.type==='choice'?'回答する':'解説を見る','reveal','primary',q.type==='choice'&&s.selected===null?'disabled':'')}</div>`:''}
 ${s.phase==='answer'?q.type==='explain'?`<div class="self-evaluation"><p>要点を説明できましたか？</p><div class="rating-buttons">${button(`${icon('X')}<span>説明できない<small>翌日</small></span>`,'rate','rating bad','data-rating="0"')}${button(`${icon('MoreHorizontal')}<span>一部できる<small>3日後</small></span>`,'rate','rating partial','data-rating="1"')}${button(`${icon('Check')}<span>説明できる<small>7〜60日後</small></span>`,'rate','rating good','data-rating="2"')}</div>${isPractice?'<small class="footnote">自主練習のため、復習予定は変更しません。</small>':''}</div>`:'' :''}
 ${s.phase==='feedback'?`<div class="feedback-actions">${button(`${s.pending.length>1?'次の問題へ':'学習を振り返る'} ${icon('ArrowRight')}`,'next','primary wide')}<a class="btn secondary wide" href="#/home">${icon('Pause')}中断してホームへ</a></div>`:''}</div>`;
}
function feedback(q,e){if(!e)return '';const good=e.rating===2;return `<section class="feedback-heading"><div class="feedback-mark ${good?'good':e.rating===1?'partial':'bad'}">${icon(good?'Check':e.rating===1?'MoreHorizontal':'RotateCcw')}</div><h1>${q.type==='choice'?(e.correct?'正解です！':'ここで理解を深めよう。'):['次の復習につなげよう。','あと一歩、理解を深めよう。','説明できました！'][e.rating]}</h1><p>${e.practice?'自主練習を記録しました。復習予定はそのままです。':`次の復習は${e.interval}日後。少しずつ、確かな理解へ。`}</p><details class="review-question"><summary>今回の問題を確認</summary><p>${esc(q.prompt)}</p>${q.type==='choice'?`<p>あなたの回答：${esc(q.choices.find(o=>o.id===e.choice)?.text)}</p><p>正解：${esc(q.choices.find(o=>o.id===q.correct)?.text)}</p>`:''}</details></section>`;}
function complete(ctx){const s=ctx.state.session,events=ctx.state.events.filter(e=>s.completed.includes(e.id));return `<section class="session-complete"><div class="completion-icon">${icon('CheckCheck')}</div><p class="completion-kicker">SESSION COMPLETE</p><h1>今日の一歩を、<br>明日の理解へ。</h1><p class="muted">おつかれさまでした。${events.length}問の学習を記録しました。</p><div class="completion-stats"><div><strong>${events.length}</strong><span>回答した問題</span></div><div><strong>${events.filter(e=>e.rating===2).length}</strong><span>説明できた・正解</span></div><div><strong>${s.total-events.length}</strong><span>未回答</span></div></div>${button(`もう一度学ぶ ${icon('ArrowRight')}`,'start','primary wide')}<a class="btn secondary wide" href="#/stats">学習統計を見る</a><a class="subtle-link" href="#/home">ホームに戻る</a></section>`;}
