import {BookOpen,House,LayoutGrid,RotateCcw,ChartNoAxesColumnIncreasing,Settings,Wifi,Database,Layers,Network,ShieldCheck,Lightbulb,ChevronRight,ChevronLeft,ArrowRight,Bookmark,Check,CheckCheck,X,Download,Upload,CloudOff,Flame,Clock,Play,Search,ExternalLink,MoreHorizontal,Target,CheckCircle2,Info,ArrowUpRight,Pause,FileText,RefreshCw} from 'lucide';
const icons={BookOpen,House,LayoutGrid,RotateCcw,ChartNoAxesColumnIncreasing,Settings,Wifi,Database,Layers,Network,ShieldCheck,Lightbulb,ChevronRight,ChevronLeft,ArrowRight,Bookmark,Check,CheckCheck,X,Download,Upload,CloudOff,Flame,Clock,Play,Search,ExternalLink,MoreHorizontal,Target,CheckCircle2,Info,ArrowUpRight,Pause,FileText,RefreshCw};
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function icon(name,cls=''){const nodes=(icons[name]||BookOpen)[2];return `<svg class="icon ${cls}" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${nodes.map(([tag,attrs])=>`<${tag} ${Object.entries(attrs).map(([k,v])=>`${k}="${esc(v)}"`).join(' ')}/>`).join('')}</svg>`;}
export const button=(label,action,cls='secondary',attrs='')=>`<button class="btn ${cls}" data-action="${action}" ${attrs}>${label}</button>`;
export const navItems=[['home','House','ホーム'],['categories','LayoutGrid','カテゴリ'],['review','RotateCcw','復習'],['stats','ChartNoAxesColumnIncreasing','統計'],['settings','Settings','設定']];
export const categoryIcon=c=>`<span class="category-icon" style="--color:${c.color}">${icon(c.icon)}</span>`;
export const progress=(value,color='var(--blue)')=>`<div class="progress-track" role="progressbar" aria-valuenow="${Math.round(value)}" aria-valuemin="0" aria-valuemax="100" aria-label="学習済みの割合"><span style="width:${Math.min(100,value)}%;background:${color}"></span></div>`;
export const empty=(name,title,body,action='')=>`<div class="empty">${icon(name)}<h3>${title}</h3><p>${body}</p>${action}</div>`;
export function header(title,subtitle='',back=''){return `<header class="page-header">${back?`<a class="icon-button" href="${back}" aria-label="戻る">${icon('ChevronLeft')}</a>`:''}<div><h1>${title}</h1>${subtitle?`<p>${subtitle}</p>`:''}</div></header>`;}
export function ratingLabel(e){if(!e)return '未学習';return e.type==='choice'?(e.correct?'正解':'不正解'):['説明できない','一部説明できる','説明できる'][e.rating];}
export function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
